### ISSUE TITLE
different background images for portrait and landscape

### ISSUE THREAD

**Issue by birdowl** [codeminders/violet-air#6]
low priority

**Comment by alexsaveliev** [comment]
in order to have both random backgrounds and portrait/landscape one we must ensure that number of vertical and horizontal background images in each slot is the same (may differ between slots, however). This way we can randomly pick a number and define two CSS classes - horizontal and vertical ones, with the same name but distinguished by the device orientation

**Comment by alexsaveliev** [comment]
closing as obsolete since we don't have canvas
